# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11leaderboard.proto\"3\n\x12LeaderboardRequest\x12\r\n\x05track\x18\x01 \x02(\r\x12\x0e\n\x06region\x18\x02 \x02(\r\"\x92\x01\n\x13LeaderboardResponse\x1a\x41\n\x05Ghost\x12\x0c\n\x04rank\x18\x01 \x02(\r\x12\x0c\n\x04time\x18\x02 \x02(\r\x12\x0b\n\x03mii\x18\x03 \x02(\x0c\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\r\x1a\x38\n\x0bLeaderboard\x12)\n\x05ghost\x18\x01 \x03(\x0b\x32\x1a.LeaderboardResponse.Ghost')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leaderboard_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEADERBOARDREQUEST._serialized_start=21
  _LEADERBOARDREQUEST._serialized_end=72
  _LEADERBOARDRESPONSE._serialized_start=75
  _LEADERBOARDRESPONSE._serialized_end=221
  _LEADERBOARDRESPONSE_GHOST._serialized_start=98
  _LEADERBOARDRESPONSE_GHOST._serialized_end=163
  _LEADERBOARDRESPONSE_LEADERBOARD._serialized_start=165
  _LEADERBOARDRESPONSE_LEADERBOARD._serialized_end=221
# @@protoc_insertion_point(module_scope)
